Create index.md
Compile7/compile7.github.io pull request #82
Opened 2022-12-05 07:30 UTC by shammirbaig

Added the blog named "How to create protected routes in React"

2022-12-05 10:29 UTC, mohammed786 commented
Hi @shammirbaig 
Please add the author details in this file - https://github.com/Compile7/compile7.github.io/blob/main/content/author.json

2022-12-05 10:30 UTC, mohammed786 requested changes
Hi @shammirbaig 
Please add the author details in this file - https://github.com/Compile7/compile7.github.io/blob/main/content/author.json

2022-12-07 05:16 UTC, mohammed786 commented on content/author.json
> +    "image": "assets/authors/AbhimanyuSinghRathore.jpg"
please use different image, or add your github id so that image will be fetch from your github account

2022-12-12 12:34 UTC, raghunath-r-a approved these changes

2022-12-12 12:35 UTC, merged